{ci debug}

diff --git a/.github/workflows/nightly-release.yaml b/.github/workflows/nightly-release.yaml
--- a/.github/workflows/nightly-release.yaml
+++ b/.github/workflows/nightly-release.yaml
@@ -3,48 +3,49 @@ name: Nightly Release
 on:
   schedule:
     - cron:  '0 0 * * ?'
+  push:
 
 
 jobs:
-  activity-check:
-    runs-on: ubuntu-latest
-    continue-on-error: true
-    outputs:
-      stale: ${{ steps.activity_check.outputs.stale }}
-    steps:
-      - name:  Activity check
-        id: activity_check
-        run:   |
-          curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '[.[]][0]' > $HOME/commit.json
-          date="$(jq -r '.commit.author.date' $HOME/commit.json)"
-          timestamp=$(date --utc -d "$date" +%s)
-          author="$(jq -r '.commit.author.name' $HOME/commit.json)"
-          url="$(jq -r '.html_url' $HOME/commit.json)"
-          hours=$(( ( $(date --utc +%s) - $timestamp ) / 3600 ))
-          rm -f $HOME/commit.json
-          echo "Latest Repository activity : $timestamp $author $url"
+  # activity-check:
+  #   runs-on: ubuntu-latest
+  #   continue-on-error: true
+  #   outputs:
+  #     stale: ${{ steps.activity_check.outputs.stale }}
+  #   steps:
+  #     - name:  Activity check
+  #       id: activity_check
+  #       run:   |
+  #         curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '[.[]][0]' > $HOME/commit.json
+  #         date="$(jq -r '.commit.author.date' $HOME/commit.json)"
+  #         timestamp=$(date --utc -d "$date" +%s)
+  #         author="$(jq -r '.commit.author.name' $HOME/commit.json)"
+  #         url="$(jq -r '.html_url' $HOME/commit.json)"
+  #         hours=$(( ( $(date --utc +%s) - $timestamp ) / 3600 ))
+  #         rm -f $HOME/commit.json
+  #         echo "Latest Repository activity : $timestamp $author $url"
 
-          STALE=false
-          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
-              echo "[WARNING] Ignoring activity limits : workflow triggered manually"
-          else
-              echo Repository active last $hours hours ago
-              if [ $hours -ge 24 ]; then
-                echo "[ERROR] Repository not updated : event<${{ github.event_name }}> not allowed to modify stale repository"
-                STALE=true
-              fi
-          fi
-          echo "stale=$STALE" >> $GITHUB_OUTPUT
+  #         STALE=false
+  #         if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
+  #             echo "[WARNING] Ignoring activity limits : workflow triggered manually"
+  #         else
+  #             echo Repository active last $hours hours ago
+  #             if [ $hours -ge 24 ]; then
+  #               echo "[ERROR] Repository not updated : event<${{ github.event_name }}> not allowed to modify stale repository"
+  #               STALE=true
+  #             fi
+  #         fi
+  #         echo "stale=$STALE" >> $GITHUB_OUTPUT
 
-          if [ "$STALE" == "true" ]; then
-            exit 1
-          fi
-        shell: bash
+  #         if [ "$STALE" == "true" ]; then
+  #           exit 1
+  #         fi
+  #       shell: bash
 
 
   build:
-    needs: activity-check
-    if: needs.activity-check.outputs.stale != 'true'
+    # needs: activity-check
+    # if: needs.activity-check.outputs.stale != 'true'
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
